# Generated by Django 4.2.1 on 2023-06-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w2core', '0002_task_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='Statu',
        ),
    ]
