# Generated by Django 4.2.1 on 2023-06-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w2core', '0003_rename_skills_skill_rename_status_statu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statu',
            new_name='Status',
        ),
    ]
