# Generated by Django 4.2.1 on 2023-06-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2core', '0004_rename_statu_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
